name: "podcast generator"
author: "Sky Shetty"
description: "Generate a podcast episode from a script"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email: 
    description: The commiter' email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter' name
    required: true
    default: ${{ github.actor }}